#!/usr/bin/env python3
"""Generate the `diagrams.scp` provider package from the SCP icon asset package.

Reads the 96px PNG icons from the SCP(v2) icon asset package and generates
Node subclasses under `<site-packages>/diagrams/scp/`, copying the icons into
`<site-packages>/resources/scp/`. The `diagrams` package resolves icon paths
relative to the site-packages directory, so both must live there.

Re-run this script after `uv sync` recreates the virtual environment.

Usage:
    uv run python scripts/generate_scp_provider.py [icon_source_dir]
"""

import os
import re
import shutil
import sys

import diagrams


CATEGORY_DIRS = {
    '1_ServiceGroup': 'servicegroup',
    '2_Service': 'service',
    '3_Resource': 'resource',
    '4_General': 'general',
}

ROOT_INIT = '''"""
SCP provides a set of icons for Samsung Cloud Platform services.
"""

from diagrams import Node


class _SCP(Node):
    _provider = "scp"
    _icon_dir = "resources/scp"

    fontcolor = "#ffffff"
'''

MODULE_HEADER = '''"""This module is automatically generated by generate_scp_provider.py. DO NOT EDIT."""

from . import _SCP


class _{class_prefix}(_SCP):
    _type = "{module}"
    _icon_dir = "resources/scp/{module}"
'''


def class_name(filename: str, prefix: str) -> str:
    """Derive a Python class name from an icon filename."""
    base = filename[len(prefix) + 1 : -len('_96px.png')]
    name = re.sub(r'[^0-9a-zA-Z_]', '', base)
    if name[0].isdigit():
        name = '_' + name
    return name


def main():
    icon_source_dir = (
        sys.argv[1]
        if len(sys.argv) > 1
        else os.path.join(
            os.path.dirname(__file__), '..', '..', '..', 'icon', 'SCP(v2)_Icons_pkg_v2.3'
        )
    )
    icon_source_dir = os.path.abspath(icon_source_dir)

    diagrams_dir = os.path.dirname(diagrams.__file__)
    site_packages_dir = os.path.dirname(diagrams_dir)

    scp_pkg_dir = os.path.join(diagrams_dir, 'scp')
    scp_resources_dir = os.path.join(site_packages_dir, 'resources', 'scp')

    os.makedirs(scp_pkg_dir, exist_ok=True)
    with open(os.path.join(scp_pkg_dir, '__init__.py'), 'w') as f:
        f.write(ROOT_INIT)

    for src_dirname, module_name in CATEGORY_DIRS.items():
        src_dir = os.path.join(icon_source_dir, src_dirname)
        if not os.path.isdir(src_dir):
            print(f'skip missing {src_dir}')
            continue

        dest_resource_dir = os.path.join(scp_resources_dir, module_name)
        os.makedirs(dest_resource_dir, exist_ok=True)

        files = sorted(f for f in os.listdir(src_dir) if f.endswith('_96px.png'))

        class_prefix = module_name.capitalize()
        lines = [MODULE_HEADER.format(class_prefix=class_prefix, module=module_name), '\n']

        for f in files:
            prefix = f.split('_')[0]
            cls = class_name(f, prefix)
            shutil.copy2(os.path.join(src_dir, f), os.path.join(dest_resource_dir, f))
            lines.append(f'\nclass {cls}(_{class_prefix}):\n    _icon = "{f}"\n')

        module_path = os.path.join(scp_pkg_dir, f'{module_name}.py')
        with open(module_path, 'w') as out:
            out.write(''.join(lines))

        print(f'Generated {module_path} with {len(files)} icons')


if __name__ == '__main__':
    main()
